### ISSUE TITLE
Houdini opens in Indie only.

### ISSUE THREAD

**Issue by GuyMicciche** [eglaubauf/egLib#2]
Hello, when I add egLib to Houdini packages, Houdini will only open in Limited Commercial (Indie) mode. Even if I click on open Houdini FX commercial. Is there a reason for this?

**Comment by eglaubauf** [comment]
Hey, 

as the assest provided are .hdalc Houdini will only open as Indie. I have no Full Houdini License, so I cannot provide full commercial assets. I added this to the readme file.
